In [1]:
import numpy as np
import pandas as pd

#### Mobile Price Prediction

In [2]:
mobile = pd.read_csv(r"C:\Users\surya\OneDrive\Desktop\AIML_CTTC\NOTES\Mobile_Price.csv")
mobile

Screen Size (inches)  RAM (GB)  Storage (GB)  Battery Capacity (mAh)  \
0                     6.2         4            64                    4000   
1                     6.1         3           128                    3110   
2                     6.5         6           256                    4500   
3                     6.7         8           128                    4300   
4                     6.4         6           128                    4200   
..                    ...       ...           ...                     ...   
287                   6.0         6            64                    3700   
288                   6.3         4           128                    4025   
289                   6.6         8           256                    5000   
290                   6.5         6           128                    4500   
291                   6.1         4            64                    3000   

     Camera Quality (MP)  Price ($)  
0                     48        500  
1                     12        800  
2                     64        600  
3                     48        700  
4                     40        550  
..                   ...        ...  
287                   12        750  
288                   32        450  
289                   48        700  
290                   64        550  
291                   16        400  

[292 rows x 6 columns]

In [3]:
mobile.isnull().sum()

Screen Size (inches)      0
RAM (GB)                  0
Storage (GB)              0
Battery Capacity (mAh)    0
Camera Quality (MP)       0
Price ($)                 0
dtype: int64

In [4]:
mobile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Screen Size (inches)    292 non-null    float64
 1   RAM (GB)                292 non-null    int64  
 2   Storage (GB)            292 non-null    int64  
 3   Battery Capacity (mAh)  292 non-null    int64  
 4   Camera Quality (MP)     292 non-null    int64  
 5   Price ($)               292 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 13.8 KB


In [5]:
mobile.dtypes

Screen Size (inches)      float64
RAM (GB)                    int64
Storage (GB)                int64
Battery Capacity (mAh)      int64
Camera Quality (MP)         int64
Price ($)                   int64
dtype: object

In [6]:
for i in mobile.columns:
     print(f"{i}: \n {mobile[i].unique()}\n")

Screen Size (inches): 
 [6.2 6.1 6.5 6.7 6.4 6.  6.3 6.6 5.8 5.7 5.9 6.8 6.9]

RAM (GB): 
 [4 3 6 8]

Storage (GB): 
 [ 64 128 256  32]

Battery Capacity (mAh): 
 [4000 3110 4500 4300 4200 3700 4025 5000 3000 3500 3800 4100 4400 3100
 4600 4700]

Camera Quality (MP): 
 [48 12 64 40 32 16 24 20]

Price ($): 
 [500 800 600 700 550 750 450 400 650 900]



#### Student Marks Prediction

In [7]:
mark = pd.read_csv(r"C:\Users\surya\OneDrive\Desktop\AIML_CTTC\NOTES\Student_Marks.csv")
mark

number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [8]:
mark.isnull().sum()

number_courses    0
time_study        0
Marks             0
dtype: int64

In [9]:
mark.dtypes

number_courses      int64
time_study        float64
Marks             float64
dtype: object

In [10]:
mark.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [11]:
for i in mark.columns:
    print(f"{i}: \n {mark[i].unique()}\n")

number_courses: 
 [3 4 6 8 5 7]

time_study: 
 [4.508 0.096 3.133 7.909 7.811 3.211 6.063 3.413 4.41  6.173 7.353 0.423
 4.218 4.274 2.908 4.26  5.719 6.08  7.711 3.977 4.733 6.126 2.051 4.875
 3.635 1.407 0.508 4.378 0.156 1.299 3.864 1.923 0.932 6.594 4.083 7.543
 2.966 7.283 6.533 7.775 0.14  2.754 3.591 1.557 1.954 2.061 3.797 4.779
 5.635 3.913 6.703 4.13  0.771 6.049 7.591 2.913 7.641 7.649 6.198 7.468
 0.376 2.438 3.606 4.869 0.13  2.142 5.473 0.55  1.395 3.948 3.736 2.518
 4.633 1.629 6.954 0.803 6.379 5.985 7.451 0.805 7.957 2.262 7.41  3.197
 1.982 6.201 4.067 1.033 1.803 6.376 4.182 2.73  5.027 6.471 3.919 3.561
 0.301 7.163 0.309 6.335]

Marks: 
 [19.202  7.734 13.811 53.018 55.299 17.822 29.889 17.264 20.348 30.862
 42.036 12.132 24.318 17.672 11.397 19.466 30.548 38.49  50.986 25.133
 22.073 35.939 12.209 28.043 16.517  6.623 12.647 26.532  9.333  8.837
 24.172  8.1   15.038 39.965 17.171 43.978 13.119 46.453 41.358 51.142
  7.336 15.725 19.771 10.429  9.742  8.924 16.703