### Predefined or Built in Function 

In [1]:
# 1. print() : To display output
print('hello world')

hello world


In [2]:
# 2.len() : return no of element in a sequence.
len([2,5,4,9,8])

5

In [4]:
# 3.sum() : returns the sum of all values in a sequence.
sum([2,5,4,9,8])

28

In [7]:
# 4.min() : returns the minimum of all values in a sequence.
min([2,5,4,9,8])

2

In [9]:
# 5.max() : returns the maximum of all values in a sequence.
max([2,5,4,9,8])

9

In [10]:
# 6.type() : returns the datatype of a function.
type([2,5,4,9,8])

list

In [11]:
# 7.id() : returns the address location of any function.
id([2,5,4,9,8])

2127604565568

In [19]:
# 8.range() : (start,stop+1,step)
for i in range(1,5,1):
    print (i)

1
2
3
4


In [13]:
# 9.ord(character): returns the ascii value of a character
ord('a') 

97

In [16]:
# 10.chr(ascii_value): returns the character associated with ascii value.
chr(58) 

':'

In [20]:
# 11.pow(base,expo): Returns the power of the function.
pow(5,4)

625

# Numpy: Numerical python

#### Numpy is a library of python that helps us to deal with arrays and to do various mathematical operations on it.

#### Array : Array is a collection of homogenous values(having similar datas),mutable(can be modified and changed),which is declared using []. Arrays are an ordered sequence(have fixed index position).

In [4]:
# importing the library to our environment.
import numpy as np

In [26]:
# to check version of numpy
np.__version__

'1.26.4'

In [27]:
# creating a 1D array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [29]:
# type()
type(a)

numpy.ndarray

In [30]:
# Creating an array from tuple : 
tup = (1,2,3,4,5,6)
b = np.array(tup)
b

array([1, 2, 3, 4, 5, 6])

In [31]:
c = np.array((1,2,3,4,5,6,'apple'))
c

array(['1', '2', '3', '4', '5', '6', 'apple'], dtype='<U11')

In [33]:
# Creating array from a dictionary
d = {1:'a',2:'b',3:'c'}
x = np.array(d)
x
# in Numpy string value are declared using 'object' datatype

array({1: 'a', 2: 'b', 3: 'c'}, dtype=object)

In [34]:
# Creating a 2D array :
# while working with a 2D array the elements are placed row-wise.
x = np.array([[1,2,3,4],[3,4,5,6],[6,7,8,9]])
x

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [35]:
# 3x3 matrix using tuple:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.array([(1,2,3),[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Array Attributes:-
# to find the shape:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [39]:
# to find the size of an array:
x = np.array([[1,2,3],[4,5,6]])
x.size

6

In [40]:
# to find the dimension of an array:
x = np.array([[1,2,3],[4,5,6]])
x.ndim

2

In [41]:
# Creating an array of different lenghths.
np.array([[1,2,3,4],[5,6,7,8],[7,8,9]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [42]:
# arange(): generates numbers between the given intervals.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Create an array of 3x2 where all values are 0.
np.array([[0,0],[0,0],[0,0]])

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
# np.zeros: generates a 0's array.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((4,5))
# 0. represents the 0's are in float(default value)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
z = np.zeros((4,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
z.dtype

dtype('float64')

In [55]:
 np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [61]:
# ones : creating an array with all values 1.
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [62]:
np.ones((4,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [63]:
# full : it will help to create an array where all values are specific.
np.full((5,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [67]:
# linspace(start_range , end_range , no. of values) : generates equally disrtributed values.
np.linspace(1,500,100)

array([  1.        ,   6.04040404,  11.08080808,  16.12121212,
        21.16161616,  26.2020202 ,  31.24242424,  36.28282828,
        41.32323232,  46.36363636,  51.4040404 ,  56.44444444,
        61.48484848,  66.52525253,  71.56565657,  76.60606061,
        81.64646465,  86.68686869,  91.72727273,  96.76767677,
       101.80808081, 106.84848485, 111.88888889, 116.92929293,
       121.96969697, 127.01010101, 132.05050505, 137.09090909,
       142.13131313, 147.17171717, 152.21212121, 157.25252525,
       162.29292929, 167.33333333, 172.37373737, 177.41414141,
       182.45454545, 187.49494949, 192.53535354, 197.57575758,
       202.61616162, 207.65656566, 212.6969697 , 217.73737374,
       222.77777778, 227.81818182, 232.85858586, 237.8989899 ,
       242.93939394, 247.97979798, 253.02020202, 258.06060606,
       263.1010101 , 268.14141414, 273.18181818, 278.22222222,
       283.26262626, 288.3030303 , 293.34343434, 298.38383838,
       303.42424242, 308.46464646, 313.50505051, 318.54

In [68]:
# identity matrix:
np.eye(6,dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [69]:
# identity matrix:
np.identity(6,dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [70]:
# Random Numbers in an array.
# random.rand() : generates a random number betweenb 0~1.
np.random.rand()

0.6409395189207165

In [72]:
# creating a 1D array with random numbers.
np.random.rand(6)

array([0.11313914, 0.4794835 , 0.44241363, 0.15162809, 0.84344596,
       0.93287554])

In [73]:
np.random.rand(3,3)

array([[0.14045833, 0.13820213, 0.81554329],
       [0.40873629, 0.98717819, 0.06847434],
       [0.75548329, 0.41560455, 0.36432059]])

In [75]:
# random.randint() : generates random integer value.
np.random.randint(1,20)

2

In [77]:
np.random.randint(1,20,(4,5))

array([[ 4, 18, 14,  2, 18],
       [19,  4,  2, 19, 18],
       [ 6,  7, 14, 15,  2],
       [ 1,  2,  8, 19,  4]])

In [78]:
# Mathematical operations on arrays 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [79]:
# add() :
np.add(a,b)

array([ 6,  8, 10, 12])

In [80]:
# subtract() : 
np.subtract(a,b)

array([-4, -4, -4, -4])

In [85]:
# multiply(): 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [86]:
# divide() : returns quotient with decimal values.
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [87]:
# floor_divide(): 
np.floor_divide(a,b)

array([0, 0, 0, 0])

In [88]:
# mod():
np.mod(a,b)

array([1, 2, 3, 4])

In [89]:
# divmod() : 
np.divmod(a,b)

(array([0, 0, 0, 0]), array([1, 2, 3, 4]))

In [90]:
# sqrt(): 
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [92]:
# power(array,expo): 
np.power(b,2)

array([25, 36, 49, 64], dtype=int32)

In [93]:
# log() : 
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [94]:
# sin() :
np.sin(b)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [95]:
# exp() : 
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [84]:
# cannot perform any operation as arrays have dfferent lengths.
c = np.array([1,2,3,4])
d = np.array([5,6,7])
np.add(c,d)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [96]:
# Statistical operations in an array.
b = np.array([23,24,58,95,64])
b

array([23, 24, 58, 95, 64])

In [97]:
# max():
np.max(b)

95

In [98]:
# min():
np.min(b)

23

In [99]:
# mean(): average
np.mean(b)

52.8

In [100]:
# median():
np.median(b)

58.0

In [101]:
# argmax(): returns the index of maximum value
np.argmax(b)

3

In [102]:
# argmin(): returns the index of minimum value
np.argmin(b)

0

In [103]:
# std(): standard deviation value
np.std(b)

27.021472942828265

In [107]:
# cumsum(): Cummulative Summation
b = np.array([23,24,58,95,64])
np.cumsum(b)

array([ 23,  47, 105, 200, 264])

In [108]:
# cumprod(): Cummulative Product
b = np.array([23,24,58,95,64])
np.cumprod(b)

array([       23,       552,     32016,   3041520, 194657280])

In [110]:
# cumproduct(): Cummulative Product
b = np.array([23,24,58,95,64])
np.cumproduct(b)

array([       23,       552,     32016,   3041520, 194657280])

In [114]:
# repeat() :
np.repeat(b,5)

array([23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 58, 58, 58, 58, 58, 95, 95,
       95, 95, 95, 64, 64, 64, 64, 64])

In [111]:
# repeates each element for a given number of times
np.repeat(b,3)

array([23, 23, 23, 24, 24, 24, 58, 58, 58, 95, 95, 95, 64, 64, 64])

In [113]:
# tile(): repeates the whole sequence for a given no of times 
np.tile(b,3)

array([23, 24, 58, 95, 64, 23, 24, 58, 95, 64, 23, 24, 58, 95, 64])

In [116]:
# where() : returns the index position of specific elemnt.
x = np.array([1,2,34,3,5,4,5,4,3,7,3,8,3,9])
np.where(x==3)

(array([ 3,  8, 10, 12], dtype=int64),)